global:
  yml_type: DET  # 配置类型, 不可更改, 可选值为DET, REC, 分别代表检测和识别
  train_model_path: ./output/model_finetune/latest.pth
  infer_model_path: ./output/model_finetune/latest.onnx
  res_save_dir: ./output/result_det
  use_infer_model: true


model:
  name: DBNet
  inner_channel: 96
  k: 50
  backbone:
    name: det_mobilenet_v3  # 轻量级backbone
    pre_trained_dir:     # 默认没有预训练模型, 因为官网提供的mobilenet的multiplier参数为1
    multiplier: 0.5  # 可选择为0.35, 0.5, 0.75, 1.0, 1.25
    use_se: false

post_process:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.7
  max_candidates: 1000
  unclip_ratio: 1.6

dataset:
  image_dir_or_path: /data/projects/task/ocr_torch/data_loader/data_det/test
  transforms:
    - ResizeForTest:
        long_size: 960
    - NormalizeImage:
    - OutputData:
        keep_keys: ["image", "src_scale"]
