global:
  yml_type: REC  # 配置类型, 不可更改, 可选值为DET, REC, 分别代表检测和识别
  train_model_path: ./output/model_rec/latest.pth
  infer_model_path: ./output/model_rec/crnn.onnx
  res_save_dir: ./output/result_rec
  use_infer_model: true
  character_json_path: ./data_loader/data_rec/chinese_chars_6695.json


model:
  name: CRNN
  rnn_type: GRU  # 可选值为GRU, LSTM
  hidden_size: 48
  num_layers: 2
  bidirectional: true
  backbone:
    name: rec_mobilenet_v3  # 轻量级backbone
    pre_trained_dir:     # 默认没有预训练模型, 因为官网提供的mobilenet的multiplier参数为1
    multiplier: 0.5  # 可选择为0.35, 0.5, 0.75, 1.0, 1.25
    use_se: false

post_process:
  name: CRnnPostProcess

dataset:
  image_dir_or_path: /data/projects/task/ocr_torch/data_loader/data_rec/train
  transforms:
    - RecResizeImg:
        image_shape: [3, 32, 320]
    - OutputData:
        keep_keys: ['image']