global:
  yml_type: REC  # 配置类型, 不可更改, 可选值为DET, REC, 分别代表检测和识别
  use_gpu: false  # 是否使用GPU
  epochs: 200
  eval_epoch: 2
  save_pth_dir: ./output/model_rec/  # pytorch模型保存地址
  init_pth_path:
  log_iter: 2  # 每隔几个iter输出一次日志
  save_epoch_iter: 2  # 每隔几个epochs保存一次模型
  max_text_len: 25  # 字符最大長度
  character_json_path: ./data_loader/data_rec/chinese_chars_6695.json

model:
  name: CRNN
  rnn_type: GRU  # 可选值为GRU, LSTM
  hidden_size: 48
  num_layers: 2
  bidirectional: true
  backbone:
    name: rec_mobilenet_v3  # 轻量级backbone
    pre_trained_dir:     # 默认没有预训练模型, 因为官网提供的mobilenet的multiplier参数为1
    multiplier: 0.5  # 可选择为0.35, 0.5, 0.75, 1.0, 1.25
    use_se: false

loss:
  name: CTCLoss

optimizer:
  name: OptimizerScheduler
  optim_method: _adam
  init_learning_rate: 0.001
  learning_schedule:
    name: LearningSchedule
    lr_method: _cosine_warmup
    warmup_epoch: 0

metrics:
  name: RecMetric
  main_indicator: acc

post_process:
  name: CRnnPostProcess

train:
  dataset:
    name: RecDataSet
    data_base_dir: /data/projects/task/ocr_torch/data_loader/data_rec/
    ano_file_path: /data/projects/task/ocr_torch/data_loader/data_rec/train.txt
    do_shuffle: true
    transforms:
      - RecAug:
          aug_prob: 0.4
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - OutputData:
          keep_keys: ['image', 'sequence_length', 'label_idx']
  dataloader:
    batch_size: 2
    num_workers: 0
    drop_last: true
    pin_memory: true


validate:
  dataset:
    name: RecDataSet
    data_base_dir: /data/projects/task/ocr_torch/data_loader/data_rec/
    ano_file_path: /data/projects/task/ocr_torch/data_loader/data_rec/train.txt
    do_shuffle: false
    transforms:
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - OutputData:
          keep_keys: ['image', 'sequence_length', 'label_idx']
  dataloader:
    batch_size: 1
    num_workers: 0
    drop_last: false
    pin_memory: false
